debug: false

default-claim-limit: 1

group-limits:
  member: 3
  vip: 5

allowed-entity-types:
  pig:
    entity-type-id: 90
    cost-money: 0.0
    cost-xp: 0
    cost-item:
      ==: org.bukkit.inventory.ItemStack
      type: GOLDEN_CARROT

