
debug: false
require-adulthood: true
require-taming: true
auto-claim-on-tame: true
unused-claim-expiry: 30d
despawn-expired-claims: false

group-limits:
  member: 10
  vip: 20

allowed-entity-types:
  pig:
    entity-type-id: 90
    cost-money: 5.0
    cost-xp: 0
  wolf:
    entity-type-id: 95
    cost-money: 5.0
    cost-xp: 0
  cat:
    entity-type-id: 98
    cost-money: 5.0
    cost-xp: 0
  cow:
    entity-type-id: 92
    cost-money: 5.0
    cost-xp: 0
  sheep:
    entity-type-id: 91
    cost-money: 5.0
  mushroom-cow:
    entity-type-id: 96
    cost-money: 5.0
  chicken:
    entity-type-id: 93
    cost-money: 5.0
  horse:
    entity-type-id: 100
    cost-money: 10

