main: ${project.main}
name: ${project.name}
author: ${project.authors}
version: ${project.version}

commands:
  livestocklock:
    aliases: [lsl, claimpet]
    permission: livestocklock.use

permissions:
  livestocklock.use:
    default: true
    description: allows access to the main command. [required for basic usage]

  livestocklock.admin:
    default: op
    children:
      livestocklock.claimforothers: true
      livestocklock.commands.*: true

  livestocklock.commands.*:
    default: op
    children:
      livestocklock.commands.claim: true
      livestocklock.commands.abandon: true
      livestocklock.commands.addplayer: true
      livestocklock.commands.removeplayer: true
      livestocklock.commands.list: true
      livestocklock.commands.ignoreclaims: true

  livestocklock.commands.ignoreclaims:
    default: op
  livestocklock.commands.claim:
    default: true
  livestocklock.commands.abandon:
    default: true
  livestocklock.commands.addplayer:
    default: true
  livestocklock.commands.removeplayer:
    default: true
  livestocklock.commands.list:
    default: true

  livestocklock.claimforothers:
    default: op


